export const ID_VALIDATION_FAIL = 'Id validation fail', //Проверка идентификатора не удалась
  RESERVE_CREATED_SUCCESS = 'Room reservation successfully created', //Резерв комнаты успешно создан
  RESERVE_FOUND_SUCCESS = 'Reserve found successfully', //Резерв найден успешно
  RESERVE_UPDATE_SUCCESS = 'Reserve update successfully', //Резерв обновлен успешно
  RESERVE_UPDATE_CONFLICT = 'Upgrading to a reserved room is prohibited:', //Обновление на зарезервированную комнату запрещено!
  RESERVE_CONFLICT = 'At this time the room is already occupied', //Резерв обновлен успешно
  RESERVE_NOTFOUND = 'Reserve not found:', //Резерв не найден
  ROOM_CREATED_SUCCESS = 'Room found successfully created', //Комната успешно создана
  ROOM_DELETE_SUCCESS = 'The room was successfully deleted', //Комната успешно удалена
  ROOM_ALL_SUCCESS = 'Data for all numbers successfully found', //Данные по всем номерам успешно найдены
  ROOM_FOUND_CONFLICT = 'The room already exists', //Комната уже существует
  ROOM_NOTFOUND = 'Rooms data not found!', //Комната не существует
  ROOM_NOT_CREATED = 'Error: Room not created!', //Ошибка: Комната не создана.
  MONGO_DUPLICATE_STATUS = 11000,
  SERVER_ERROR = 'Ошибка сервера',
  DEFAULT_PORT = 3000;
